name: First workflow
on: workflow_dispatch
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      -name: Print "Hello Word"
      run: echo "Hello word"
      -name: Print "Just testing"
      run:echo "baby"
  
       
