name: First workflow
on: workflow_trigger
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps: 
      -name: Print Welcome to my bank App
       run:echo "Welcome"
      -name: Print Check Balance
       run: echo "Checking"
       
